include: package:lint/strict.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - lib/l10n/generated/*.dart
    - test/appium/**
    - coverage/**
    - build/**
  errors:
    todo: warning
    fixme: warning
    hack: info

