name: pile_of_shame
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  intl: any
  path_provider: ^2.1.0
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: any
  json_serializable: any
  riverpod_generator: any
  riverpod_lint: any
  custom_lint: any
  mockito: any
  # Testing path_provider requires these dependencies
  path_provider_platform_interface: ^2.1.0
  plugin_platform_interface: any

flutter:
  uses-material-design: true

  assets:
    - assets/platforms/icons/microsoft/
    - assets/platforms/text_logos/microsoft/
    - assets/platforms/icons/nintendo/
    - assets/platforms/text_logos/nintendo/
    - assets/platforms/icons/pc/
    - assets/platforms/text_logos/pc/
    - assets/platforms/icons/sony/
    - assets/platforms/text_logos/sony/
