name: pile_of_shame
description: An offline list for the game status of all your video games
publish_to: 'none'
version: 0.1.9+14

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  intl: any
  path_provider: ^2.1.0
  riverpod_annotation: ^2.1.1
  dynamic_color: ^1.6.6
  shared_preferences: ^2.2.0
  file_picker: ^5.3.3
  flutter_animate: ^4.2.0+1
  animations: ^2.0.7
  flutter_colorpicker: ^1.0.3
  transparent_image: ^2.0.1
  flutter_native_splash: ^2.3.2
  package_info_plus: ^4.1.0
  uuid: ^3.0.7
  share_plus: ^7.1.0
  flutter_file_dialog: ^3.0.2
  flutter_sticky_header: ^0.6.5
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: any
  json_serializable: any
  riverpod_generator: any
  riverpod_lint: any
  custom_lint: any
  mockito: any
  # Testing path_provider requires these dependencies
  path_provider_platform_interface: ^2.1.0
  plugin_platform_interface: any
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  shaders:
    - shaders/game_controller_shader.frag

  assets:
    - assets/app/
    - assets/languages/
    - assets/misc/
    - assets/platforms/controllers/microsoft/
    - assets/platforms/controllers/misc/
    - assets/platforms/controllers/nintendo/
    - assets/platforms/controllers/pc/
    - assets/platforms/controllers/sony/
    - assets/platforms/icons/microsoft/
    - assets/platforms/icons/misc/
    - assets/platforms/icons/nintendo/
    - assets/platforms/icons/pc/
    - assets/platforms/icons/sony/
    - assets/platforms/shader/sony/
    - assets/platforms/text_logos/microsoft/
    - assets/platforms/text_logos/misc/
    - assets/platforms/text_logos/nintendo/
    - assets/platforms/text_logos/pc/
    - assets/platforms/text_logos/sony/
