// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVZ8zQAXKWnlfQ4eAxtebXzzU-0VdYvas',
    appId: '1:404159068955:web:acde347b22803a451b71be',
    messagingSenderId: '404159068955',
    projectId: 'pile-of-shame-56515',
    authDomain: 'pile-of-shame-56515.firebaseapp.com',
    storageBucket: 'pile-of-shame-56515.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX_XbGRb4Ed2eC7rmbWJwL4L1B4Qqla4Q',
    appId: '1:404159068955:android:5bbea759dc0309341b71be',
    messagingSenderId: '404159068955',
    projectId: 'pile-of-shame-56515',
    storageBucket: 'pile-of-shame-56515.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn8dAx1V6oBSHyhbUBMACBTXCwYhJIov4',
    appId: '1:404159068955:ios:f7d07cad24f16d4f1b71be',
    messagingSenderId: '404159068955',
    projectId: 'pile-of-shame-56515',
    storageBucket: 'pile-of-shame-56515.appspot.com',
    iosClientId: '404159068955-65p2mtjtui9b3j9tcpg8rkcr4csvhjc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pileOfShame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn8dAx1V6oBSHyhbUBMACBTXCwYhJIov4',
    appId: '1:404159068955:ios:f7d07cad24f16d4f1b71be',
    messagingSenderId: '404159068955',
    projectId: 'pile-of-shame-56515',
    storageBucket: 'pile-of-shame-56515.appspot.com',
    iosClientId: '404159068955-65p2mtjtui9b3j9tcpg8rkcr4csvhjc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pileOfShame',
  );
}
