name: misc_utils
description: Miscellaneous utilities that are useful in different projects
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  animations: ^2.0.8
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_file_dialog: ^3.0.2
  freezed_annotation: ^2.4.1
  intl: any
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  transparent_image: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  lint: ^2.1.2
  # Testing path_provider requires these dependency
  path_provider_platform_interface: ^2.1.0
  # Testing path_provider requires this dependency
  plugin_platform_interface: any

flutter: