name: misc_utils
description: Miscellaneous utilities that are useful in different projects
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_file_dialog: ^3.0.2
  intl: any
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  custom_lint: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  # Testing path_provider requires these dependency
  path_provider_platform_interface: ^2.1.0
  # Testing path_provider requires this dependency
  plugin_platform_interface: any

flutter: