name: flutter-build-and-run-tests
on:
  pull_request:
    branches:
      - master

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Setup environment
      - name: Java - setup SDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17.x"
          cache: gradle
      - name: Flutter - setup SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
        # Fetch dependencies and generate code
      - name: Flutter - fetch dependencies
        run: flutter pub get
      - name: Flutter - generate Localizations
        run: flutter gen-l10n
      - name: Flutter - generate code using build_runner
        run: dart run build_runner build
        # Check if the application can build
      - name: Flutter - build application
        run: flutter build appbundle --debug
        # Run unit tests
      - name: Flutter - run unit tests
        run: flutter test